"""init2

Revision ID: 464e4f2a05d6
Revises: f2bf702bfc40
Create Date: 2024-04-23 17:37:50.012389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464e4f2a05d6'
down_revision = 'f2bf702bfc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
